% initialize USRP receiver and transmitter
    
function radio_xx = USRP_init(rx_length, address, whichx)
    %TX_RX_INIT Summary of this function goes here
    %   Detailed explanation goes here
    platform = "N200/N210/USRP2";
    % address  = '192.168.10.2';
    USRPGain            = 5;  % Set USRP radio gain
    USRPCenterFrequency = 915*1e6;  % Set USRP radio center frequency
    
    if whichx == "tx"
        radio_xx = comm.SDRuTransmitter(...
                            'Platform',             platform, ...
                            'IPAddress',            address, ...
                            'CenterFrequency',      USRPCenterFrequency, ...
                            'Gain',                 USRPGain);
    elseif whichx == "rx"
        radio_xx = comm.SDRuReceiver(...
                        'Platform',             platform, ...
                        'IPAddress',            address, ...
                        'CenterFrequency',      USRPCenterFrequency, ...
                        'Gain',                 5, ...
                        'SamplesPerFrame',      rx_length, ...
                        'OutputDataType',       'double') ;
    end
                   
end